---
- name: Include MetalLB + App + Ingress deployment tasks
  import_tasks: pods.yaml

- name: Include argocd
  import_tasks: argocd.yaml

- name: Include Metrics Server Setup
  import_tasks: metrics-server.yaml
