---
# Kubernetes YUM repository 정보
k8s_repo:
  name: kubernetes
  baseurl: "https://pkgs.k8s.io/core:/stable:/v1.33/rpm/"
  gpgkey: "https://pkgs.k8s.io/core:/stable:/v1.33/rpm/repodata/repomd.xml.key"
  exclude: "kubelet kubeadm kubectl cri-tools kubernetes-cni"

# 설치할 Kubernetes 패키지 목록
k8s_packages:
  - kubelet
  - kubeadm
  - kubectl

# .bashrc 에 추가할 kubectl 설정
kubectl_bashrc_lines:
  - 'source <(kubectl completion bash)'
  - 'alias k=kubectl'
  - 'complete -o default -F __start_kubectl k'
